ROOT_DOMAIN = ['ac', 'academy', 'accountants', 'actor', 'ad', 'ae', 'aero',
               'af', 'ag', 'agency', 'ai', 'airforce', 'al', 'am', 'an', 'ao',
               'aq', 'ar', 'archi', 'arpa', 'as', 'asia', 'associates', 'at',
               'au', 'audio', 'autos', 'aw', 'ax', 'axa', 'az',
               'ba', 'bar', 'bargains', 'bayern', 'bb', 'bd', 'be', 'beer',
               'berlin', 'best', 'bf', 'bg', 'bh', 'bi', 'bid', 'bike', 'biz',
               'bj', 'bl', 'black', 'blackfriday', 'blue', 'bm', 'bn', 'bo',
               'boutique', 'bq', 'br', 'bs', 'bt', 'build', 'builders', 'buzz',
               'bv', 'bw', 'by', 'bz',
               'ca', 'cab', 'camera', 'camp', 'capital', 'cards', 'care',
               'career', 'careers', 'cash', 'cat', 'catering', 'cc', 'cd',
               'center', 'ceo', 'cf', 'cg', 'ch', 'cheap', 'christmas',
               'church', 'ci', 'citic', 'ck', 'cl', 'claims', 'cleaning',
               'clinic', 'clothing', 'club', 'cm', 'cn', 'co', 'codes',
               'coffee', 'college', 'cologne', 'com', 'community', 'company',
               'computer', 'construction', 'contractors', 'cooking', 'cool',
               'coop', 'country', 'cr', 'credit', 'creditcard', 'cruises',
               'cu', 'cv', 'cw', 'cx', 'cy', 'cz',
               'dance', 'dating', 'de', 'democrat', 'dental', 'desi',
               'diamonds', 'digital', 'directory', 'discount', 'dj', 'dk',
               'dm', 'do', 'domains', 'dz',
               'ec', 'edu', 'education', 'ee', 'eg', 'eh', 'email',
               'engineering', 'enterprises', 'equipment', 'er', 'es', 'estate',
               'et', 'eu', 'eus', 'events', 'exchange', 'expert', 'exposed',
               'fail', 'farm', 'feedback', 'fi', 'finance', 'financial',
               'fish', 'fishing', 'fitness', 'fj', 'fk', 'flights', 'florist',
               'fm', 'fo', 'foo', 'foundation', 'fr', 'frogans', 'fund',
               'furniture', 'futbol',
               'ga', 'gal', 'gallery', 'gb', 'gd', 'ge', 'gf', 'gg', 'gh',
               'gi', 'gift', 'gl', 'glass', 'globo', 'gm', 'gmo', 'gn', 'gop',
               'gov', 'gp', 'gq', 'gr', 'graphics', 'gratis', 'gripe', 'gs',
               'gt', 'gu', 'guide', 'guitars', 'guru', 'gw', 'gy',
               'haus', 'hiphop', 'hk', 'hm', 'hn', 'holdings', 'holiday',
               'homes', 'horse', 'house', 'hr', 'ht', 'hu',
               'id', 'ie', 'il', 'im', 'immobilien', 'in', 'industries',
               'info', 'institute', 'insure', 'int', 'international',
               'investments', 'io', 'iq', 'ir', 'is', 'it',
               'je', 'jetzt', 'jm', 'jo', 'jobs', 'jp', 'juegos',
               'kaufen', 'ke', 'kg', 'kh', 'ki', 'kim', 'kitchen', 'kiwi',
               'km', 'kn', 'koeln', 'kp', 'kr', 'kred', 'kw', 'ky', 'kz',
               'la', 'land', 'lb', 'lc', 'lease', 'li', 'life', 'lighting',
               'limited', 'limo', 'link', 'lk', 'loans', 'london', 'lr', 'ls',
               'lt', 'lu', 'luxe', 'luxury', 'lv', 'ly',
               'ma', 'management', 'mango', 'marketing', 'mc', 'md', 'me',
               'media', 'meet', 'menu', 'mf', 'mg', 'mh', 'miami', 'mil', 'mk',
               'ml', 'mm', 'mn', 'mo', 'mobi', 'moda', 'moe', 'monash',
               'moscow', 'motorcycles', 'mp', 'mq', 'mr', 'ms', 'mt', 'mu',
               'museum', 'mv', 'mw', 'mx', 'my', 'mz',
               'na', 'nagoya', 'name', 'nc', 'ne', 'net', 'neustar', 'nf',
               'ng', 'ni', 'ninja', 'nl', 'no', 'np', 'nr', 'nu', 'nyc', 'nz',
               'okinawa', 'om', 'onl', 'org',
               'pa', 'paris', 'partners', 'parts', 'pe', 'pf', 'pg', 'ph',
               'photo', 'photography', 'photos', 'pics', 'pictures', 'pink',
               'pk', 'pl', 'plumbing', 'pm', 'pn', 'post', 'pr', 'pro',
               'productions', 'properties', 'ps', 'pt', 'pub', 'pw', 'py',
               'qa', 'qpon', 'quebec',
               're', 'recipes', 'red', 'reisen', 'ren', 'rentals', 'repair',
               'report', 'rest', 'reviews', 'rich', 'ro', 'rocks', 'rodeo',
               'rs', 'ru', 'ruhr', 'rw', 'ryukyu',
               'sa', 'saarland', 'sb', 'sc', 'schule', 'sd', 'se', 'services',
               'sexy', 'sg', 'sh', 'shiksha', 'shoes', 'si', 'singles', 'sj',
               'sk', 'sl', 'sm', 'sn', 'so', 'social', 'sohu', 'solar',
               'solutions', 'soy', 'sr', 'ss', 'st', 'su', 'supplies',
               'supply', 'support', 'surgery', 'sv', 'sx', 'sy', 'systems',
               'sz',
               'tattoo', 'tax', 'tc', 'td', 'technology', 'tel', 'tf', 'tg',
               'th', 'tienda', 'tips', 'tj', 'tk', 'tl', 'tm', 'tn', 'to',
               'today', 'tokyo', 'tools', 'town', 'toys', 'tp', 'tr', 'trade',
               'training', 'travel', 'tt', 'tv', 'tw', 'tz',
               'ua', 'ug', 'uk', 'um', 'university', 'uno', 'us', 'uy', 'uz',
               'va', 'vacations', 'vc', 've', 'vegas', 'ventures', 'vg', 'vi',
               'viajes', 'villas', 'vision', 'vn', 'vodka', 'vote', 'voting',
               'voto', 'voyage', 'vu',
               'wang', 'watch', 'webcam', 'wed', 'wf', 'wien', 'wiki', 'works',
               'ws', 'wtc', 'wtf'
               'co.kr', 'ne.kr', 'or.kr', 're.kr', 'pe.kr', 'go.kr', 'mil.kr',
               'ac.kr', 'hs.kr', 'ms.kr', 'es.kr', 'sc.kr', 'kg.kr',
               'seoul.kr', 'busan.kr', 'daegu.kr', 'incheon.kr', 'gwangju.kr',
               'daejeon.kr', 'ulsan.kr', 'gyeonggi.kr', 'gangwon.kr',
               'chungbuk.kr', 'chungnam.kr', 'jeonbuk.kr', 'jeonnam.kr',
               'gyeongbuk.kr', 'gyeongnam.kr', 'jeju.kr']
